Repository Labs-EU4/hackathon-portal-client, pull requests merged in 2020-03, with the labels that each got.

#26 Testing/store/events 🧪
  src/components/templates/__tests__/__snapshots__/HackathonForm.test.js.snap
  src/store/events/__tests__/actions.test.js
Labels: Testing

#27 Testing/store/events participants 🧪
  src/store/eventParticipants/__tests__/actions.test.js
Labels: Testing

#28 Testing/store/projectSubmission 🧪
  src/store/projectSubmission/__tests__/actions.test.js
  src/utils/mockData.js
Labels: Testing

#29 Testing/store/participantTeams 🧪
  src/components/templates/__tests__/__snapshots__/HackathonForm.test.js.snap
  src/store/participantTeams/__tests__/actions.test.js
  src/utils/mockData.js
Labels: Testing

#32 Add 5 tests to TeamView
  src/components/templates/HackathonProjects.js
  src/components/templates/__tests__/HackathonProjects.test.js
  src/components/templates/__tests__/TeamView.test.js
  src/components/templates/__tests__/__snapshots__/TeamView.test.js.snap
Labels: Testing

#31 Testing/templates/HackathonSingleProject 🧪
  src/components/templates/__tests__/HackathonSingleProject.test.js
  src/utils/mockData.js
Labels: Testing

#33 Testing/user profile 🧪
  src/components/templates/__tests__/UserProfile.test.js
  src/components/templates/__tests__/__snapshots__/UserProfile.test.js.snap
Labels: Testing

#34 Add 4 tests to LoginPage
  src/components/templates/__tests__/TeamView.test.js
  src/components/views/__tests__/LoginPage.test.js
  src/components/views/__tests__/__snapshots__/LoginPage.test.js.snap
Labels: Testing

#36 Testing/SignupPage 🧪
  src/components/views/__tests__/SignupPage.test.js
  src/components/views/__tests__/__snapshots__/SignupPage.test.js.snap
Labels: Testing

#38 Testing/ParticipantsubmissionPage 🧪
  src/components/templates/__tests__/__snapshots__/HackathonSingleProject.test.js.snap
  src/components/views/__tests__/ParticipantSubmissionPage.test.js
  src/components/views/__tests__/__snapshots__/ParticipantSubmissionPage.test.js.snap
  src/utils/mockData.js
Labels: Testing

#40 HackathonSinglePage 🧪
  src/components/templates/__tests__/__snapshots__/HackathonForm.test.js.snap
  src/components/views/__tests__/HackathonSinglePage.test.js
  src/components/views/__tests__/__snapshots__/HackathonSinglePage.test.js.snap
  src/components/views/__tests__/__snapshots__/ParticipantSubmissionPage.test.js.snap
Labels: Testing

#41 Testing/HackathonProjectsPage 🧪
  src/components/views/__tests__/HackathonProjectsPage.test.js
  src/components/views/__tests__/__snapshots__/HackathonProjectsPage.test.js.snap
Labels: Testing

#42 Testing/HackathonFormPage 🧪
  src/components/templates/__tests__/__snapshots__/AddParticipantTeams.test.js.snap
  src/components/templates/__tests__/__snapshots__/AddTeammates.test.js.snap
  src/components/templates/__tests__/__snapshots__/EventOnboarding.test.js.snap
  src/components/templates/__tests__/__snapshots__/HackathonForm.test.js.snap
  src/components/templates/__tests__/__snapshots__/HackathonProjects.test.js.snap
  src/components/templates/__tests__/__snapshots__/HackathonSingle.test.js.snap
  src/components/templates/__tests__/__snapshots__/HackathonSingleProject.test.js.snap
  src/components/templates/__tests__/__snapshots__/UserProfile.test.js.snap
  src/components/views/__tests__/HackathonFormPage.test.js
  src/components/views/__tests__/__snapshots__/HackathonFormPage.test.js.snap
  src/components/views/__tests__/__snapshots__/HackathonProjectPage.test.js.snap
  src/components/views/__tests__/__snapshots__/HackathonProjectsPage.test.js.snap
  src/components/views/__tests__/__snapshots__/HackathonSinglePage.test.js.snap
  src/components/views/__tests__/__snapshots__/ParticipantSubmissionPage.test.js.snap
  src/utils/mockData.js
Labels: Testing

#47 Testing userprofileform
  src/components/templates/__tests__/UserProfileForm.test.js
  src/components/templates/__tests__/__snapshots__/UserProfileForm.test.js.snap
Labels: Testing

#45 added the tests for the userprofileform
  src/components/templates/__tests__/UserProfileForm.test.js
  src/components/templates/__tests__/__snapshots__/UserProfileForm.test.js.snap
Labels: Testing

#46 Testing/UserProfileFormPage 🧪
  src/components/views/__tests__/UserProfileFormPage.test.js
  src/components/views/__tests__/__snapshots__/UserProfileFormPage.test.js.snap
  src/utils/mockData.js
Labels: Testing

#48 Testing/CreateTeam.js 🧪
  src/components/templates/__tests__/CreateTeam.test.js
  src/components/templates/__tests__/__snapshots__/CreateTeam.test.js.snap
Labels: Testing

#49 Testing/debug
  .coveralls.yml
  src/components/molecules/__tests__/__snapshots__/MediaIcons.test.js.snap
  src/components/molecules/__tests__/__snapshots__/SocialMedia.test.js.snap
  src/components/organisms/__tests__/Header.test.js
  src/components/organisms/__tests__/__snapshots__/Header.test.js.snap
  src/components/templates/AddParticipantTeams.jsx
  src/components/templates/AddTeammates.jsx
  src/components/templates/__tests__/AddTeammates.test.js
  src/components/templates/__tests__/TeamView.test.js
  src/components/templates/__tests__/__snapshots__/AddParticipantTeams.test.js.snap
  src/components/templates/__tests__/__snapshots__/AddTeammates.test.js.snap
  src/components/templates/widgets.js
  src/components/views/__tests__/__snapshots__/HackathonFormPage.test.js.snap
Labels: Testing, bug

#51 Testing/App_PrivateRoute 🧪
  src/__test__/App.test.js
  src/__test__/__snapshots__/App.test.js.snap
Labels: Testing

#44 created a test for userprofilepage
  src/components/templates/UserProfileForm.jsx
  src/components/templates/__tests__/UserProfileForm.test.js
  src/components/views/__tests__/UserProfilePage.test.js
  src/components/views/__tests__/__snapshots__/UserProfilePage.test.js.snap
  src/utils/mockData.js
Labels: Testing

#35 Code Quality, Bug Fixes, Validation
  src/components/atoms/Heading.js
  src/components/atoms/TagsInput.js
  src/components/molecules/EventCard.js
  src/components/organisms/Form.js
  src/components/styles/templates/HackathonSingleStyling.js
  src/components/templates/HackathonForm.js
Labels: Code Quality, bug, enhancement

#43 Testing/views/Dashboard 🧪
  src/components/views/__tests__/Dashboard.test.js
Labels: Testing

#52 Cq debug
  src/components/molecules/__tests__/__snapshots__/MediaIcons.test.js.snap
  src/components/molecules/__tests__/__snapshots__/SocialMedia.test.js.snap
  src/components/organisms/Form.js
  src/components/templates/CreateTeam.jsx
  src/components/templates/UserProfileForm.jsx
  src/components/templates/__tests__/__snapshots__/HackathonForm.test.js.snap
  src/components/templates/__tests__/__snapshots__/UserProfileForm.test.js.snap
  src/components/views/__tests__/__snapshots__/HackathonFormPage.test.js.snap
Labels: Code Quality, bug

#53 Testing/EditHackathon 🧪
  src/__test__/__snapshots__/App.test.js.snap
  src/components/molecules/__tests__/__snapshots__/MediaIcons.test.js.snap
  src/components/molecules/__tests__/__snapshots__/SocialMedia.test.js.snap
  src/components/templates/__tests__/EditHackathon.test.js
  src/components/templates/__tests__/__snapshots__/EditHackathon.test.js.snap
  src/components/templates/__tests__/__snapshots__/EventOnboarding.test.js.snap
  src/components/templates/__tests__/__snapshots__/HackathonForm.test.js.snap
  src/components/templates/__tests__/__snapshots__/UserProfile.test.js.snap
  src/components/views/__tests__/__snapshots__/Dashboard.test.js.snap
  src/components/views/__tests__/__snapshots__/HackathonFormPage.test.js.snap
  src/components/views/__tests__/__snapshots__/PageNotFound.test.js.snap
Labels: Testing

#50 Cq badges
  .gitignore
  README.md
  src/components/molecules/__tests__/__snapshots__/MediaIcons.test.js.snap
  src/components/molecules/__tests__/__snapshots__/SocialMedia.test.js.snap
  src/components/templates/__tests__/__snapshots__/HackathonForm.test.js.snap
Labels: bug, enhancement

#56 Testing/resetPassword 🧪
  src/components/molecules/__tests__/__snapshots__/MediaIcons.test.js.snap
  src/components/molecules/__tests__/__snapshots__/SocialMedia.test.js.snap
  src/components/views/resetPassword/__tests__/ResetPassword.test.js
  src/components/views/resetPassword/__tests__/__snapshots__/ResetPassword.test.js.snap
Labels: Testing

#57 Testing/resetPasswordConfirmation 🧪
  src/components/views/resetPassword/__tests__/ResetPasswordConfirmation.test.js
  src/components/views/resetPassword/__tests__/__snapshots__/ResetPasswordConfirmation.test.js.snap
Labels: Testing

#58 Testing/NewPassword 🧪
  src/components/views/resetPassword/__tests__/NewPassword.test.js
  src/components/views/resetPassword/__tests__/__snapshots__/NewPassword.test.js.snap
Labels: Testing

#68 Atoms refactor logo
  package-lock.json
  package.json
  src/__test__/__snapshots__/App.test.js.snap
  src/components/atoms/Logo.jsx
  src/components/molecules/__tests__/__snapshots__/MediaIcons.test.js.snap
  src/components/molecules/__tests__/__snapshots__/PublicNav.test.js.snap
  src/components/molecules/__tests__/__snapshots__/SocialMedia.test.js.snap
  src/components/organisms/Footer.js
  src/components/organisms/__tests__/__snapshots__/Footer.test.js.snap
  src/components/organisms/__tests__/__snapshots__/Header.test.js.snap
  src/components/templates/__tests__/__snapshots__/AddParticipantTeams.test.js.snap
  src/components/templates/__tests__/__snapshots__/AddTeammates.test.js.snap
  src/components/templates/__tests__/__snapshots__/CreateTeam.test.js.snap
  src/components/templates/__tests__/__snapshots__/EditHackathon.test.js.snap
  src/components/templates/__tests__/__snapshots__/EventOnboarding.test.js.snap
  src/components/templates/__tests__/__snapshots__/HackathonForm.test.js.snap
  src/components/templates/__tests__/__snapshots__/HackathonProjects.test.js.snap
  src/components/templates/__tests__/__snapshots__/HackathonSingle.test.js.snap
  src/components/templates/__tests__/__snapshots__/HackathonSingleProject.test.js.snap
  src/components/templates/__tests__/__snapshots__/TeamView.test.js.snap
  src/components/templates/__tests__/__snapshots__/UserProfile.test.js.snap
  src/components/templates/__tests__/__snapshots__/UserProfileForm.test.js.snap
  src/components/templates/__tests__/__snapshots__/Widgets.test.js.snap
  src/components/views/__tests__/__snapshots__/Dashboard.test.js.snap
  src/components/views/__tests__/__snapshots__/HackathonFormPage.test.js.snap
  src/components/views/__tests__/__snapshots__/HackathonProjectPage.test.js.snap
  src/components/views/__tests__/__snapshots__/HackathonProjectsPage.test.js.snap
  src/components/views/__tests__/__snapshots__/HackathonSinglePage.test.js.snap
  src/components/views/__tests__/__snapshots__/LoginPage.test.js.snap
  src/components/views/__tests__/__snapshots__/PageNotFound.test.js.snap
  src/components/views/__tests__/__snapshots__/ParticipantSubmissionPage.test.js.snap
  src/components/views/__tests__/__snapshots__/SignupPage.test.js.snap
  src/components/views/__tests__/__snapshots__/UserProfileFormPage.test.js.snap
  src/components/views/resetPassword/__tests__/__snapshots__/NewPassword.test.js.snap
  src/components/views/resetPassword/__tests__/__snapshots__/ResetPassword.test.js.snap
  src/components/views/resetPassword/__tests__/__snapshots__/ResetPasswordConfirmation.test.js.snap
Labels: Code Quality

#80 Refactor UserHeader organisms, fix tests
  src/assets/styles/atoms/HeaderContainer.js
  src/assets/styles/atoms/HeaderContainerStyling.js
  src/assets/styles/atoms/WideHeader.js
  src/assets/styles/atoms/WideHeaderStyling.js
  src/components/molecules/PublicNav.jsx
  src/components/organisms/UserHeader.jsx
  src/components/templates/__tests__/CreateTeam.test.js
  src/components/templates/__tests__/HackathonForm.test.js
Labels: Code Quality, Testing

#84 Refactor/hackathon projects
  src/components/templates/HackathonProjects.js
  src/components/templates/__tests__/__snapshots__/HackathonProjects.test.js.snap
  src/components/views/AboutPage.jsx
  src/components/views/Dashboard.jsx
  src/components/views/__tests__/HackathonProjectsPage.test.js
  src/components/views/__tests__/__snapshots__/Dashboard.test.js.snap
  src/components/views/__tests__/__snapshots__/HackathonProjectsPage.test.js.snap
Labels: Code Quality

#86 Refactor user events dashboard 🖼
  report.20200319.105901.2359.0.001.json
  src/App.jsx
  src/__test__/__snapshots__/App.test.js.snap
  src/assets/styles/atoms/Label.js
  src/assets/styles/templates/UserEventsDashboardStyling.js
  src/components/organisms/PrivateRoute.jsx
  src/components/organisms/UserHeader.jsx
  src/components/templates/UserEventsDashboard.jsx
  src/components/templates/__tests__/__snapshots__/AddParticipantTeams.test.js.snap
  src/components/templates/__tests__/__snapshots__/AddTeammates.test.js.snap
  src/components/templates/__tests__/__snapshots__/CreateTeam.test.js.snap
  src/components/templates/__tests__/__snapshots__/EditHackathon.test.js.snap
  src/components/templates/__tests__/__snapshots__/EventOnboarding.test.js.snap
  src/components/templates/__tests__/__snapshots__/HackathonForm.test.js.snap
  src/components/templates/__tests__/__snapshots__/HackathonProjects.test.js.snap
  src/components/templates/__tests__/__snapshots__/HackathonSingle.test.js.snap
  src/components/templates/__tests__/__snapshots__/HackathonSingleProject.test.js.snap
  src/components/templates/__tests__/__snapshots__/UserProfile.test.js.snap
  src/components/templates/__tests__/__snapshots__/UserProfileForm.test.js.snap
  src/components/views/Dashboard.jsx
  src/components/views/__tests__/__snapshots__/Dashboard.test.js.snap
  src/components/views/__tests__/__snapshots__/HackathonFormPage.test.js.snap
  src/components/views/__tests__/__snapshots__/HackathonProjectPage.test.js.snap
  src/components/views/__tests__/__snapshots__/HackathonProjectsPage.test.js.snap
  src/components/views/__tests__/__snapshots__/HackathonSinglePage.test.js.snap
  src/components/views/__tests__/__snapshots__/ParticipantSubmissionPage.test.js.snap
  src/components/views/__tests__/__snapshots__/UserProfileFormPage.test.js.snap
Labels: Code Quality, Testing, enhancement

#90 Templates-UserOnboarding
  src/components/templates/UserOnboarding.jsx
  src/components/views/__tests__/LoginPage.test.js
  src/components/views/__tests__/SignupPage.test.js
  src/components/views/__tests__/__snapshots__/Dashboard.test.js.snap
  src/components/views/__tests__/__snapshots__/LoginPage.test.js.snap
  src/components/views/__tests__/__snapshots__/SignupPage.test.js.snap
Labels: Code Quality, enhancement

#93 Refactor team view 🖼
  src/__test__/__snapshots__/App.test.js.snap
  src/assets/styles/templates/TeamViewStyling.js
  src/components/molecules/__tests__/__snapshots__/MediaIcons.test.js.snap
  src/components/molecules/__tests__/__snapshots__/SocialMedia.test.js.snap
  src/components/templates/CreateTeam.jsx
  src/components/templates/EventOnboarding.js
  src/components/templates/HackathonSingle.js
  src/components/templates/TeamView.jsx
  src/components/templates/UserProfileForm.jsx
  src/components/templates/__tests__/CreateTeam.test.js
  src/components/templates/__tests__/__snapshots__/CreateTeam.test.js.snap
  src/components/templates/__tests__/__snapshots__/EventOnboarding.test.js.snap
  src/components/templates/__tests__/__snapshots__/TeamView.test.js.snap
  src/components/views/__tests__/__snapshots__/Dashboard.test.js.snap
Labels: Code Quality, enhancement

#95 User profile refactor 🖼
  src/components/templates/UserProfile.jsx
  src/components/templates/__tests__/UserProfile.test.js
  src/components/templates/__tests__/UserProfileForm.test.js
  src/components/templates/__tests__/__snapshots__/UserProfile.test.js.snap
  src/components/templates/__tests__/__snapshots__/UserProfileForm.test.js.snap
  src/components/views/UserProfilePage.jsx
  src/components/views/__tests__/UserProfilePage.test.js
  src/components/views/__tests__/__snapshots__/UserProfilePage.test.js.snap
Labels: Code Quality, enhancement

#98 amend map categories for individual key
  src/__test__/__snapshots__/App.test.js.snap
  src/assets/styles/templates/AddTeammatesStyling.js
  src/assets/styles/templates/UserEventsDashboardStyling.js
  src/components/molecules/__tests__/__snapshots__/MediaIcons.test.js.snap
  src/components/molecules/__tests__/__snapshots__/SocialMedia.test.js.snap
  src/components/organisms/Nav.jsx
  src/components/organisms/PSProjectTitle.jsx
  src/components/templates/AddParticipantTeams.jsx
  src/components/templates/HackathonForm.js
  src/components/templates/UserEventsDashboard.jsx
  src/components/templates/UserProfileForm.jsx
  src/components/templates/__tests__/__snapshots__/EditHackathon.test.js.snap
  src/components/templates/__tests__/__snapshots__/HackathonForm.test.js.snap
  src/components/views/__tests__/__snapshots__/Dashboard.test.js.snap
  src/components/views/__tests__/__snapshots__/HackathonFormPage.test.js.snap
Labels: Code Quality, Testing, bug

#102 Amend app/nav warning
  .gitignore
  src/__test__/__snapshots__/App.test.js.snap
  src/components/molecules/__tests__/__snapshots__/MediaIcons.test.js.snap
  src/components/molecules/__tests__/__snapshots__/SocialMedia.test.js.snap
  src/components/organisms/Nav.jsx
Labels: Code Quality, Testing, bug

#106 Bug - Join Event Button
  src/components/organisms/EventCard.jsx
  src/components/templates/EventOnboarding.js
  src/components/templates/EventOnboarding.jsx
  src/components/templates/UserEventsDashboard.jsx
Labels: bug

#107 Feature google map/Location,marker
  src/components/templates/__tests__/__snapshots__/EditHackathon.test.js.snap
  src/components/templates/__tests__/__snapshots__/HackathonForm.test.js.snap
  src/components/views/ResultsPage.jsx
  src/components/views/__tests__/__snapshots__/Dashboard.test.js.snap
  src/components/views/__tests__/__snapshots__/HackathonFormPage.test.js.snap
  src/components/views/anon.png
Labels: enhancement

#113 EventCard Buttons
  src/components/organisms/EventCard.jsx
  src/components/templates/UserEventsDashboard.jsx
  src/components/views/LoginPage.jsx
  src/components/views/ResultsPage.jsx
Labels: enhancement

#124 Codequality spinner
  src/__test__/__snapshots__/App.test.js.snap
  src/components/molecules/Spinner.jsx
  src/components/organisms/Form.jsx
  src/components/templates/__tests__/__snapshots__/HackathonProjects.test.js.snap
  src/components/templates/__tests__/__snapshots__/HackathonSingle.test.js.snap
  src/components/views/__tests__/__snapshots__/HackathonProjectsPage.test.js.snap
  src/components/views/__tests__/__snapshots__/HackathonSinglePage.test.js.snap
  src/components/views/__tests__/__snapshots__/LoginPage.test.js.snap
  src/components/views/__tests__/__snapshots__/SignupPage.test.js.snap
Labels: Code Quality, bug, enhancement

#131 Spinner 🖼
  src/components/molecules/Spinner.jsx
  src/components/organisms/Form.jsx
Labels: bug, enhancement
