Repository Labs-EU4/hackathon-portal-client, pull requests merged in 2020-02, with the labels that each got.

#1 Adding API URLs dependent on stage of the branch in the pipeline
  netlify.toml
  package.json
  src/App.jsx
Labels: DevOps

#2 Removing console.log statement to check environmental variables
  src/App.jsx
Labels: DevOps

#8 Cq/modules
  src/components/atoms/CheckGroup.js
  src/components/atoms/Checkbox.js
  src/components/molecules/PublicNav.js
  src/components/styles/modules/NavStyling.js
  src/components/templates/AddParticipantTeams.jsx
  src/components/templates/AddTeammates.jsx
  src/components/templates/__tests__/__snapshots__/EventOnboarding.test.js.snap
  src/components/templates/widgets.js
Labels: Code Quality

#9 Cq atoms
  package.json
  src/components/atoms/Input.js
  src/components/atoms/Row.js
  src/components/atoms/Select.js
  src/components/atoms/TagsInput.js
  src/components/molecules/Checkbox.js
  src/components/molecules/Nav.js
  src/components/molecules/TextArea.js
  src/components/styles/GlobalStyles.js
  src/components/styles/atoms/TagsInput.css
  src/components/styles/molecules/CheckboxStyling.js
  src/components/styles/molecules/NavStyling.js
  src/components/styles/molecules/TextAreaStyling.js
  src/components/templates/HackathonForm.js
  src/components/templates/HackathonSingle.js
  src/components/templates/ParticipantSubmission.js
  src/components/templates/UserProfileForm.jsx
  src/components/templates/__tests__/__snapshots__/EventOnboarding.test.js.snap
Labels: Code Quality

#10 Removed irrelevant hooks
  src/hooks/events.js
Labels: Code Quality

#11 Testing/hackathon form 🧪
  src/components/templates/HackathonForm.js
  src/components/templates/__tests__/HackathonForm.test.js
  src/components/templates/__tests__/__snapshots__/EventOnboarding.test.js.snap
  src/components/templates/__tests__/__snapshots__/HackathonForm.test.js.snap
Labels: Testing

#20 Tests on Header 🧪
  src/components/organisms/__tests__/Header.test.js
  src/components/organisms/__tests__/__snapshots__/Header.test.js.snap
  src/components/templates/__tests__/__snapshots__/EventOnboarding.test.js.snap
  src/components/templates/__tests__/__snapshots__/HackathonForm.test.js.snap
Labels: Testing

#23 Added a mock function on the test file, in order to be able to have p…
  src/components/templates/HackathonProjects.js
  src/components/templates/__tests__/HackathonProjects.test.js
Labels: Testing, bug

#22 Testing/footer
  src/components/organisms/__tests__/Footer.test.js
  src/components/organisms/__tests__/__snapshots__/Footer.test.js.snap
  src/serviceWorker.js
Labels: Code Quality, Testing

#24 Testing/pageNotFound 🧪
  src/components/views/__tests__/PageNotFound.test.js
  src/components/views/__tests__/__snapshots__/PageNotFound.test.js.snap
Labels: Testing

#25 Testing/store/user 🧪
  src/components/templates/__tests__/__snapshots__/HackathonForm.test.js.snap
  src/store/user/__tests__/actions.test.js
  src/store/user/actions.js
Labels: Testing
